### ISSUE TITLE
create example apps for isa lib in nim

### ISSUE THREAD

**Issue by despiegk** [nimscale/isa#2]
- erasure coding of file (& decoding)
- compression & crc of file (& decompression)

all done in nim using our lib

**Comment by andrzejslomskii** [comment]
Please check this nim file and binary file on Ubuntu 16.04 64bit machine.
[nimfiles.zip](https://github.com/nimscale/isa/files/662425/nimfiles.zip)

**Comment by despiegk** [comment]
in nimfiles.zip I only find the CRC example, as mentioned above was also erasure coding.
Please put in this repo and simple example is enough, one which is easy to use
