### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by despiegk** [nimscale/isa#6]
implemented in nim using the bindings

**Comment by andrzejslomskii** [comment]
Would you please explain more detail about this task?
It is enough to build the isa-l?

**Comment by despiegk** [comment]
- you can try to use c2nim
    - and maybe need to adjust here and there
- we need a nimble installable set of bindings
- from out of nim we can then use all functionality of the intel ISA library

**Comment by despiegk** [comment]
implement examples in https://github.com/nimscale/isa/tree/master/examples
